training:
  num_epochs: 50
  batch_size: 32
  learning_rate: 0.0001

model:
  name: "multi_scale_conv1d"  # Name of the model to use from the registry
  # options: 
  # "dual_pathway_fft"
  # "simplest_possible"
  # "multi_scale_conv1d"

signal:
  length: 2048
  sampling_rate: 1024

visualization:
  num_predictions: 10