model:
  gradient_refinement:
    base_step_size: 0.001
    enabled: true
    max_iterations: 10
  name: pinn_peak_detector
signal:
  length: 512
  sampling_rate: 512
training:
  batch_size: 32
  early_stopping:
    min_delta: 0.0001
    patience: 200
  learning_rate: 0.0001
  num_epochs: 2000
visualization:
  num_predictions: 10
