model:
  gradient_refinement:
    base_step_size: 0.001
    enabled: false
    max_iterations: 10
  name: simplest_possible
signal:
  length: 1024
  sampling_rate: 512
  add_complex_signal: false
training:
  batch_size: 32
  early_stopping:
    min_delta: 0.0001
    patience: 2000
  learning_rate: 0.001
  num_epochs: 2000
loss:
  name: gradient_aware
  position_weight: 1.0
  magnitude_weight: 1.0
  gradient_weight: 2.0
  second_derivative_weight: 1.0
visualization:
  num_predictions: 10
