loss:
  name: gradient_aware
model:
  gradient_refinement:
    base_step_size: 0.001
    enabled: true
    max_iterations: 10
  name: multi_scale_conv1d
signal:
  length: 2048
  sampling_rate: 1024
curriculum:
  complex_noise:
    start_amplitude: 0.0    # Start with no noise
    end_amplitude: 0.2      # Maximum noise amplitude
    min_amplitude: 0.05     # Minimum threshold for adding noise
    epochs_to_max: 10000    # Number of epochs to reach maximum amplitude
  learning_rate:
    start: 5.0e-5          # Initial learning rate
    end: 1.0e-6            # Final learning rate
    epochs_to_min: 50000    # Epochs to reach minimum learning rate
  loss_weights:
    start:                  # Initial loss weights
      position: 100.0
      magnitude: 1.0
      gradient: 1.0e-8
      second_derivative: 1.0e-4
    final:                  # Final loss weight values
      position: 100.0
      magnitude: 1.0
      gradient: 1.0e-6
      second_derivative: 1.0e-2
    epochs_to_final: 20000  # Epochs to reach final weights
training:
  batch_size: 32
  early_stopping:
    min_delta: 0.0001
    patience: 1000
  num_epochs: 100
visualization:
  num_predictions: 10
  plot_frequency: 50
