loss:
  gradient_weight: 1.0e-08
  magnitude_weight: 1.0
  name: gradient_aware
  position_weight: 100.0
  second_derivative_weight: 0.0001
model:
  gradient_refinement:
    base_step_size: 0.001
    enabled: true
    max_iterations: 10
  name: pinn_peak_detector
signal:
  add_complex_signal: true
  length: 2048
  sampling_rate: 1024
training:
  batch_size: 32
  early_stopping:
    min_delta: 0.0001
    patience: 1000
  learning_rate: 5.0e-05
  num_epochs: 1000000
visualization:
  num_predictions: 10
  plot_frequency: 500
