curriculum:
  complex_noise:
    end_amplitude: 0.2
    epochs_to_max: 100000
    min_amplitude: 0.05
    start_amplitude: 0.2
  learning_rate:
    end: 1.0e-06
    epochs_to_min: 100000
    start: 1.0e-05
  loss_weights:
    epochs_to_final: 100000
    final:
      gradient: 0.00001
      magnitude: 0.01
      position: 10.0
      second_derivative: 0.00001
    start:
      gradient: 0.00001
      magnitude: 0.01
      position: 10.0
      second_derivative: 0.00001
loss:
  name: peak_loss
model:
  name: pinn_peak_detector
signal:
  length: 2048
  sampling_rate: 1024
training:
  batch_size: 1024
  early_stopping:
    min_delta: 0.0001
    patience: 2444
  num_epochs: 24444
visualization:
  num_predictions: 10
  plot_frequency: 100
