curriculum:
  complex_noise:
    end_amplitude: 0.02
    epochs_to_max: 10000
    min_amplitude: 0.05
    start_amplitude: 0.02
  learning_rate:
    end: 1.0e-07
    epochs_to_min: 10000
    start: 1.0e-06
  loss_weights:
    epochs_to_final: 100000
    final:
      magnitude: 1.0
      position: 10.0
      # Optional physics-informed terms (0 to disable)
      gradient: 0.0  # Set to 1.0e-4 to enable
      second_derivative: 0.0  # Set to 1.0e-4 to enable
    start:
      magnitude: 1.0
      position: 10.0
      # Optional physics-informed terms (0 to disable)
      gradient: 0.0  # Set to 1.0e-4 to enable
      second_derivative: 0.0  # Set to 1.0e-4 to enable
loss:
  name: peak_loss
model:
  name: simplest_possible
signal:
  length: 2048
  sampling_rate: 1024
training:
  batch_size: 32
  early_stopping:
    min_delta: 0.0001
    patience: 5000
  num_epochs: 100
visualization:
  num_predictions: 10
  plot_frequency: 100
