training:
  num_epochs: 20
  batch_size: 32
  learning_rate: 0.0001

model:
  name: "dual_pathway_fft"  # Name of the model to use from the registry

signal:
  length: 2048
  sampling_rate: 1024

visualization:
  num_predictions: 32 