base_config:
  loss:
    name: gradient_aware
  model:
    gradient_refinement:
      base_step_size: 0.001
      enabled: true
      max_iterations: 10
    name: multi_scale_conv1d
  signal:
    length: 2048
    sampling_rate: 1024
  curriculum:
    complex_noise:
      start_amplitude: 0.05    # Start with no noise
      end_amplitude: 0.2      # Maximum noise amplitude
      min_amplitude: 0.05     # Minimum thresholds for adding noise
      epochs_to_max: 10000    # Number of epochs to reach maximum amplitude
    learning_rate:
      start: 1.0e-2         # Initial learning rate
      end: 1.0e-6            # Final learning rate
      epochs_to_min: 10000    # Epochs to reach minimum learning rate
    loss_weights:
      start:                  # Initial loss weights
        position: 100.0
        magnitude: 10.0
        gradient: 1.0e-9
        second_derivative: 1.0e-5
      final:                  # Final loss weight values
        position: 100.0
        magnitude: 1.0
        gradient: 1.0e-8
        second_derivative: 1.0e-3
      epochs_to_final: 100000  # Epochs to reach final weights
  training:
    batch_size: 32
    early_stopping:
      min_delta: 0.0001
      patience: 10000
    num_epochs: 1000000
  visualization:
    num_predictions: 10
    plot_frequency: 500

experiments:
  - name: "simple_model_test"
    model:
      name: "simplest_possible"

  - name: "dual_pathway_fft"
    model:
      name: "dual_pathway_fft"
      
  - name: "multi_scale_conv1d"
    model:
      name: "multi_scale_conv1d"

  - name: "attention_dilated_conv1d"
    model:
      name: "attention_dilated_conv1d"

  - name: "transformer_conv1d"
    model:
      name: "transformer_conv1d"

  - name: "spectral_peak_detector"
    model:
      name: "spectral_peak_detector"

  - name: "pinn_peak_detector"
    model:
      name: "pinn_peak_detector"
    