base_config:
  curriculum:
    complex_noise:
      end_amplitude: 0.02
      epochs_to_max: 10000
      min_amplitude: 0.05
      start_amplitude: 0.02
    learning_rate:
      end: 1.0e-07
      epochs_to_min: 10000
      start: 1.0e-06
    loss_weights:
      epochs_to_final: 100000
      final:
        magnitude: 1.0
        position: 10.0
        # Optional physics-informed terms (1e-10 to effectively disable)
        gradient: 1.0e-10  # 1.0e-4 
        second_derivative: 1.0e-10  # 1.0e-4
      start:
        magnitude: 1.0
        position: 10.0
        # Optional physics-informed terms (1e-10 to effectively disable)
        gradient: 1.0e-10  # 1.0e-4 
        second_derivative: 1.0e-10  #  1.0e-4
  loss:
    name: peak_loss
  signal:
    length: 2048
    sampling_rate: 1024
  training:
    batch_size: 32
    early_stopping:
      min_delta: 0.0001
      patience: 5000
    num_epochs: 100
  visualization:
    num_predictions: 10
    plot_frequency: 100

experiments:
  - name: "simplest_possible"
    model:
      name: "simplest_possible"

  - name: "attention_dilated_conv1d"
    model:
      name: "attention_dilated_conv1d"

  - name: "pinn_peak_detector"
    model:
      name: "pinn_peak_detector"
    