base_config:
  signal:
    length: 1024
    sampling_rate: 512
  visualization:
    num_predictions: 10
    plot_frequency: 500
  training:
    batch_size: 32
    num_epochs: 1000000
    learning_rate: 0.0001
    early_stopping:
      patience: 1000
      min_delta: 0.0001  
  model:
    gradient_refinement:
      enabled: true
      base_step_size: 0.001
      max_iterations: 10
  loss:
    name: gradient_aware
    position_weight: 100.0
    magnitude_weight: 1.0
    gradient_weight: 0.00000001
    second_derivative_weight: 0.0001

experiments:
  - name: "simple_model_test"
    model:
      name: "simplest_possible"

  - name: "dual_pathway_fft"
    model:
      name: "dual_pathway_fft"
      
  - name: "multi_scale_conv1d"
    model:
      name: "multi_scale_conv1d"

  - name: "attention_dilated_conv1d"
    model:
      name: "attention_dilated_conv1d"

  - name: "transformer_conv1d"
    model:
      name: "transformer_conv1d"

  - name: "spectral_peak_detector"
    model:
      name: "spectral_peak_detector"

  - name: "pinn_peak_detector"
    model:
      name: "pinn_peak_detector"
    