base_config:
  curriculum:
    complex_noise:
      end_amplitude: 0.2
      epochs_to_max: 88888
      min_amplitude: 0.05
      start_amplitude: 0.2
    learning_rate:
      end: 1.0e-05
      epochs_to_min: 88888
      start: 1.0e-04
    loss_weights:
      epochs_to_final: 88888
      final:
        gradient: 0.0001
        magnitude: 0.05
        position: 10.0
        second_derivative: 0.0001
      start:
        gradient: 0.0001
        magnitude: 0.05
        position: 10.0
        second_derivative: 0.0001
  loss:
    name: peak_loss
  signal:
    length: 2048
    sampling_rate: 1024
  training:
    batch_size: 1024
    early_stopping:
      min_delta: 0.0001
      patience: 2222
    num_epochs: 88888
  visualization:
    num_predictions: 10
    plot_frequency: 1000

experiments:
  - name: "simplest_possible"
    model:
      name: "simplest_possible"

  - name: "attention_dilated_conv1d"
    model:
      name: "attention_dilated_conv1d"

  - name: "pinn_peak_detector"
    model:
      name: "pinn_peak_detector"
    