base_config:
  curriculum:
    complex_noise:
      end_amplitude: 0.2
      epochs_to_max: 10000
      min_amplitude: 0.05
      start_amplitude: 0.2
    learning_rate:
      end: 1.0e-07
      epochs_to_min: 10000
      start: 1.0e-06
    loss_weights:
      epochs_to_final: 100000
      final:
        gradient: 1.0e-10 #1.0e-05
        magnitude: 1.0e-10 #0.01
        position: 10.0
        second_derivative: 1.0e-10 #1.0e-03
      start:
        gradient: 1.0e-10 #1.0e-05
        magnitude: 1.0e-10 #0.01
        position: 10.0
        second_derivative: 1.0e-10 #1.0e-03
  loss:
    name: simple_mse
  model:
    gradient_refinement:
      base_step_size: 0.001
      enabled: false
      max_iterations: 10
    name: multi_scale_conv1d
  signal:
    length: 2048
    sampling_rate: 1024
  training:
    batch_size: 32
    early_stopping:
      min_delta: 0.0001
      patience: 5000
    num_epochs: 1000000
  visualization:
    num_predictions: 10
    plot_frequency: 1000

experiments:
  - name: "simple_model_test"
    model:
      name: "simplest_possible"

  - name: "dual_pathway_fft"
    model:
      name: "dual_pathway_fft"
      
  - name: "multi_scale_conv1d"
    model:
      name: "multi_scale_conv1d"

  - name: "attention_dilated_conv1d"
    model:
      name: "attention_dilated_conv1d"

  - name: "transformer_conv1d"
    model:
      name: "transformer_conv1d"

  - name: "spectral_peak_detector"
    model:
      name: "spectral_peak_detector"

  - name: "pinn_peak_detector"
    model:
      name: "pinn_peak_detector"
    