base_config:
  signal:
    length: 512
    sampling_rate: 512
  visualization:
    num_predictions: 10
  training:
    batch_size: 32
    num_epochs: 20
    learning_rate: 0.0001
    early_stopping:
      patience: 20
      min_delta: 0.0001  
  model:
    gradient_refinement:
      enabled: true
      base_step_size: 0.001
      max_iterations: 10

experiments:
  - name: "simple_model_test"
    model:
      name: "simplest_possible"

  - name: "dual_pathway_fft"
    model:
      name: "dual_pathway_fft"
      
  - name: "multi_scale_conv1d"
    model:
      name: "multi_scale_conv1d"

  - name: "attention_dilated_conv1d"
    model:
      name: "attention_dilated_conv1d"

  - name: "transformer_conv1d"
    model:
      name: "transformer_conv1d"

  - name: "spectral_peak_detector"
    model:
      name: "spectral_peak_detector"

  - name: "pinn_peak_detector"
    model:
      name: "pinn_peak_detector"
    